const FOUNDATION = [
  {"en": "0", "th": "suun", "script": "ศูนย์", "cat": "numbers", "note": "decimal point = jùd"},
  {"en": "1", "th": "nèung", "script": "หนึ่ง", "cat": "numbers"},
  {"en": "2", "th": "sǎwng", "script": "สอง", "cat": "numbers"},
  {"en": "3", "th": "sǎam", "script": "สาม", "cat": "numbers"},
  {"en": "4", "th": "sèe", "script": "สี่", "cat": "numbers"},
  {"en": "5", "th": "hâa", "script": "ห้า", "cat": "numbers"},
  {"en": "6", "th": "hòk", "script": "หก", "cat": "numbers"},
  {"en": "7", "th": "jèd", "script": "เจ็ด", "cat": "numbers"},
  {"en": "8", "th": "bpàaed", "script": "แปด", "cat": "numbers"},
  {"en": "9", "th": "gâo", "script": "เก้า", "cat": "numbers"},
  {"en": "10", "th": "sìp", "script": "สิบ", "cat": "numbers"},
  {"en": "11", "th": "sìp-èd", "script": "สิบเอ็ด", "cat": "numbers", "note": "11 uses 'èd' not 'nèung'"},
  {"en": "12", "th": "sìp-sǎwng", "script": "สิบสอง", "cat": "numbers"},
  {"en": "13", "th": "sìp-sǎam", "script": "สิบสาม", "cat": "numbers"},
  {"en": "14", "th": "sìp-sèe", "script": "สิบสี่", "cat": "numbers"},
  {"en": "15", "th": "sìp-hâa", "script": "สิบห้า", "cat": "numbers"},
  {"en": "16", "th": "sìp-hòk", "script": "สิบหก", "cat": "numbers"},
  {"en": "17", "th": "sìp-jèd", "script": "สิบเจ็ด", "cat": "numbers"},
  {"en": "18", "th": "sìp-bpàaed", "script": "สิบแปด", "cat": "numbers"},
  {"en": "19", "th": "sìp-gâo", "script": "สิบเก้า", "cat": "numbers"},
  {"en": "20", "th": "yêe-sìp", "script": "ยี่สิบ", "cat": "numbers", "note": "exception: 'yêe' not 'sǎwng'"},
  {"en": "21", "th": "yêe-sìp-èd", "script": "ยี่สิบเอ็ด", "cat": "numbers"},
  {"en": "30", "th": "sǎam-sìp", "script": "สามสิบ", "cat": "numbers"},
  {"en": "36", "th": "sǎam-sìp-hòk", "script": "สามสิบหก", "cat": "numbers"},
  {"en": "40", "th": "sèe-sìp", "script": "สี่สิบ", "cat": "numbers"},
  {"en": "50", "th": "hâa-sìp", "script": "ห้าสิบ", "cat": "numbers"},
  {"en": "52", "th": "hâa-sìp-sǎwng", "script": "ห้าสิบสอง", "cat": "numbers"},
  {"en": "60", "th": "hòk-sìp", "script": "หกสิบ", "cat": "numbers"},
  {"en": "63", "th": "hòk-sìp-sǎam", "script": "หกสิบสาม", "cat": "numbers"},
  {"en": "70", "th": "jèd-sìp", "script": "เจ็ดสิบ", "cat": "numbers"},
  {"en": "75", "th": "jèd-sìp-hâa", "script": "เจ็ดสิบห้า", "cat": "numbers"},
  {"en": "80", "th": "bpàaed-sìp", "script": "แปดสิบ", "cat": "numbers"},
  {"en": "88", "th": "bpàaed-sìp-bpàaed", "script": "แปดสิบแปด", "cat": "numbers"},
  {"en": "90", "th": "gâo-sìp", "script": "เก้าสิบ", "cat": "numbers"},
  {"en": "100", "th": "nèung-róy", "script": "หนึ่งร้อย", "cat": "numbers"},
  {"en": "1000", "th": "nèung-phan", "script": "หนึ่งพัน", "cat": "numbers"},
  {"en": "10000", "th": "nèung-mèun", "script": "หนึ่งหมื่น", "cat": "numbers"},
  {"en": "100000", "th": "nèung-sǎaen", "script": "หนึ่งแสน", "cat": "numbers"},
  {"en": "1000000", "th": "nèung-láan", "script": "หนึ่งล้าน", "cat": "numbers"},
  {"en": "I (masculine)", "th": "phǒm", "cat": "pronouns", "script": "ผม", "note": "polite male"},
  {"en": "I (feminine)", "th": "chǎn / dìchǎn", "cat": "pronouns", "script": "ฉัน / ดิฉัน", "note": "polite female"},
  {"en": "you", "th": "khun", "cat": "pronouns", "script": "คุณ"},
  {"en": "he / she / it", "th": "khǎo", "cat": "pronouns", "script": "เขา", "note": "same for all genders"},
  {"en": "we / us", "th": "phûuak-rao / rao", "cat": "pronouns", "script": "พวกเรา / เรา"},
  {"en": "they / them", "th": "phûuak-khǎo", "cat": "pronouns", "script": "พวกเขา"},
  {"en": "man", "th": "man", "cat": "pronouns", "script": "มัน", "note": "informal / animals / objects"},
  {"en": "Hello / Goodbye", "th": "sa-wàd-dee", "cat": "greetings", "script": "สวัสดี"},
  {"en": "Good night", "th": "raa-dtree-sa-wàd", "cat": "greetings", "script": "ราตรีสวัสดิ์"},
  {"en": "How are you?", "th": "khun sa-baai dee mǎi", "cat": "greetings", "script": "คุณสบายดีไหม"},
  {"en": "I am fine / well", "th": "phǒm sa-baai dee / a-nàa", "cat": "greetings", "script": "ผมสบายดี"},
  {"en": "Pleased to meet you", "th": "yin-dee thêe dâi rúu-jàk", "cat": "greetings", "script": "ยินดีที่ได้รู้จัก"},
  {"en": "Goodbye / farewell", "th": "laa gawn", "cat": "greetings", "script": "ลาก่อน"},
  {"en": "Thank you", "th": "khàwp khun", "cat": "greetings", "script": "ขอบคุณ"},
  {"en": "Excuse me / Sorry", "th": "khǎw thôod (general)", "cat": "greetings", "script": "ขอโทษ"},
  {"en": "What did you say?", "th": "khâo thôod à-rai", "cat": "greetings", "script": "เข้าใจอะไร"},
  {"en": "Never mind / That's alright", "th": "mâi bpen rai", "cat": "greetings", "script": "ไม่เป็นไร"},
  {"en": "Come quickly!", "th": "raw sèk-khràu", "cat": "greetings", "script": "รีบสักครู่"},
  {"en": "Just a moment", "th": "raw sèk-khràu", "cat": "greetings", "script": "รอสักครู่"},
  {"en": "You're welcome", "th": "yin-dee", "cat": "greetings", "script": "ยินดี"},
  {"en": "I have a headache", "th": "phǒm bpùuad hǔua", "cat": "greetings", "script": "ผมปวดหัว"},
  {"en": "He has a cold", "th": "khǎo bpen wâd", "cat": "greetings", "script": "เขาเป็นหวัด"},
  {"en": "I am very busy", "th": "phǒm yûng mâak", "cat": "greetings", "script": "ผมยุ่งมาก"},
  {"en": "Please come in", "th": "chern khâang-nai", "cat": "greetings", "script": "เชิญข้างใน"},
  {"en": "I've forgotten", "th": "phǒm leuam lǎaeo", "cat": "greetings", "script": "ผมลืมแล้ว"},
  {"en": "To arrive late", "th": "maa sǎai", "cat": "greetings", "script": "มาสาย"},
  {"en": "How much is it?", "th": "raa-khaa thâo-rai", "cat": "greetings", "script": "ราคาเท่าไร"},
  {"en": "What time is it?", "th": "wae-laa thâo-rai", "cat": "greetings", "script": "เวลาเท่าไร"},
  {"en": "What time is it? (alt)", "th": "gee moong lǎaeo", "cat": "greetings", "script": "กี่โมงแล้ว"},
  {"en": "See you again", "th": "phóp gan mài", "cat": "greetings", "script": "พบกันใหม่"},
  {"en": "See you tomorrow", "th": "phóp gan phrûng-nêe", "cat": "greetings", "script": "พบกันพรุ่งนี้"},
  {"en": "See you later", "th": "diaao phóp gan", "cat": "greetings", "script": "เดี๋ยวพบกัน"},
  {"en": "No problem", "th": "mâi mee bpan-hǎa", "cat": "greetings", "script": "ไม่มีปัญหา"},
  {"en": "I don't agree", "th": "phǒm mâi hěn dûuai", "cat": "greetings", "script": "ผมไม่เห็นด้วย"},
  {"en": "I am sorry (regret)", "th": "phǒm sǐia-jai (to express regret)", "cat": "greetings", "script": "ผมเสียใจ"},
  {"en": "have", "th": "mee", "cat": "patterns", "script": "มี", "note": "subject + mee + object"},
  {"en": "do not have", "th": "mâi mee", "cat": "patterns", "script": "ไม่มี", "note": "subject + mâi mee + object"},
  {"en": "Do you have? (question)", "th": "mee ... mǎi", "cat": "patterns", "script": "มี...ไหม", "note": "mee + object + mǎi"},
  {"en": "Does Peter have any friends?", "th": "Peter mee phêuuan mǎi", "cat": "patterns", "script": "ปีเตอร์มีเพื่อนไหม"},
  {"en": "Does Jane have a phone?", "th": "Jane mee meu-thêuu mǎi", "cat": "patterns", "script": "เจนมีมือถือไหม"},
  {"en": "Does this shop have any coffee?", "th": "raan nêe mee gaa-faae mǎi", "cat": "patterns", "script": "ร้านนี้มีกาแฟไหม"},
  {"en": "Do we have any pizza?", "th": "rao mee phíd-sǎa mǎi", "cat": "patterns", "script": "เรามีพิซซ่าไหม"},
  {"en": "many / a lot", "th": "lǎai", "cat": "quantifiers", "script": "หลาย", "note": "object + lǎai + classifier"},
  {"en": "many people", "th": "lǎai khon", "cat": "quantifiers", "script": "หลายคน"},
  {"en": "many books", "th": "lǎai lêm", "cat": "quantifiers", "script": "หลายเล่ม"},
  {"en": "many cars", "th": "lǎai khan", "cat": "quantifiers", "script": "หลายคัน"},
  {"en": "many houses", "th": "lǎai lǎng", "cat": "quantifiers", "script": "หลายหลัง"},
  {"en": "many rooms", "th": "lǎai hâwng", "cat": "quantifiers", "script": "หลายห้อง"},
  {"en": "many newspapers", "th": "lǎai cha-bàp", "cat": "quantifiers", "script": "หลายฉบับ"},
  {"en": "not many / a few", "th": "mâi gee", "cat": "quantifiers", "script": "ไม่กี่", "note": "object + mâi gee + classifier"},
  {"en": "not many people", "th": "mâi gee khon", "cat": "quantifiers", "script": "ไม่กี่คน"},
  {"en": "not many books", "th": "mâi gee lêm", "cat": "quantifiers", "script": "ไม่กี่เล่ม"},
  {"en": "not many rooms", "th": "mâi gee hâwng", "cat": "quantifiers", "script": "ไม่กี่ห้อง"},
  {"en": "not many houses", "th": "mâi gee lǎng", "cat": "quantifiers", "script": "ไม่กี่หลัง"},
  {"en": "only one / alone / just one", "th": "diao / khon diao", "cat": "quantifiers", "script": "เดียว / คนเดียว", "note": "classifier + diao"},
  {"en": "just one person", "th": "khon diao", "cat": "quantifiers", "script": "คนเดียว"},
  {"en": "just one room", "th": "hâwng diao", "cat": "quantifiers", "script": "ห้องเดียว"},
  {"en": "just one dog", "th": "mǎa dtuua diao", "cat": "quantifiers", "script": "หมาตัวเดียว"},
  {"en": "only one book", "th": "nǎng-sêu lêm diao", "cat": "quantifiers", "script": "หนังสือเล่มเดียว"},
  {"en": "only one TV", "th": "thee-wee krêuang diao", "cat": "quantifiers", "script": "ทีวีเครื่องเดียว"},
  {"en": "just once (one time)", "th": "kráng diao", "cat": "quantifiers", "script": "ครั้งเดียว"},
  {"en": "just one (alone)", "th": "khâang diao", "cat": "quantifiers", "script": "ข้างเดียว", "note": "just one side"},
  {"en": "kilogram", "th": "gi-loo", "cat": "shopping", "script": "กิโล"},
  {"en": "100 grams", "th": "kneed", "cat": "shopping", "script": "ขีด"},
  {"en": "litre", "th": "lít", "cat": "shopping", "script": "ลิตร"},
  {"en": "half", "th": "khrêung", "cat": "shopping", "script": "ครึ่ง"},
  {"en": "rice", "th": "khâao", "cat": "shopping", "script": "ข้าว"},
  {"en": "milk", "th": "nom", "cat": "shopping", "script": "นม"},
  {"en": "orange juice", "th": "nám-sôm", "cat": "shopping", "script": "น้ำส้ม"},
  {"en": "apple juice", "th": "nám-aaep-bpêm", "cat": "shopping", "script": "น้ำแอปเปิ้ล"},
  {"en": "tea", "th": "chaa", "cat": "shopping", "script": "ชา"},
  {"en": "beef", "th": "néuua", "cat": "shopping", "script": "เนื้อ"},
  {"en": "pork", "th": "muu", "cat": "shopping", "script": "หมู"},
  {"en": "chicken", "th": "gài", "cat": "shopping", "script": "ไก่"},
  {"en": "sugar", "th": "nám-dtaan", "cat": "shopping", "script": "น้ำตาล"},
  {"en": "cooking oil", "th": "nám-man-phêud", "cat": "shopping", "script": "น้ำมันพืช"},
  {"en": "half a kilo of beef", "th": "néuua khrêung gi-loo", "cat": "shopping", "script": "เนื้อครึ่งกิโล"},
  {"en": "150 grams of chicken", "th": "gài nèung kneed khrêung", "cat": "shopping", "script": "ไก่หนึ่งขีดครึ่ง"},
  {"en": "a litre of milk", "th": "nom nèung lít", "cat": "shopping", "script": "นมหนึ่งลิตร"},
  {"en": "3 bottles of cooking oil", "th": "nám-man-phêud sǎam khùuad", "cat": "shopping", "script": "น้ำมันพืชสามขวด"},
  {"en": "Question tag (universal)", "th": "châi mǎi", "cat": "patterns", "script": "ใช่ไหม", "note": "Add to end of any statement"},
  {"en": "isn't it?", "th": "châi mǎi", "cat": "patterns", "script": "ใช่ไหม"},
  {"en": "aren't they?", "th": "châi mǎi", "cat": "patterns", "script": "ใช่ไหม", "note": "same word for all"},
  {"en": "isn't he/she?", "th": "châi mǎi", "cat": "patterns", "script": "ใช่ไหม"},
  {"en": "Answer YES to tag question", "th": "châi", "cat": "patterns", "script": "ใช่"},
  {"en": "Answer NO to tag question", "th": "mâi châi", "cat": "patterns", "script": "ไม่ใช่"},
  {"en": "That is John, isn't it?", "th": "nân kheuu John, châi mǎi", "cat": "patterns", "script": "นั่นคือจอห์น ใช่ไหม"},
  {"en": "That is a table, isn't it?", "th": "nân bpen dtoe, châi mǎi", "cat": "patterns", "script": "นั่นเป็นโต๊ะ ใช่ไหม"},
  {"en": "He is not here, is he?", "th": "khǎo mâi yùu thêe-nêe, châi mǎi", "cat": "patterns", "script": "เขาไม่อยู่ที่นี่ ใช่ไหม"},
  {"en": "It's not tall, is it?", "th": "man mâi sǔung, châi mǎi", "cat": "patterns", "script": "มันไม่สูง ใช่ไหม"},
  {"en": "how many?", "th": "gee", "cat": "patterns", "script": "กี่", "note": "gee + classifier"},
  {"en": "How many cars do you have?", "th": "khun mee ród-yon gee khan", "cat": "patterns", "script": "คุณมีรถยนต์กี่คัน"},
  {"en": "How many friends does he have?", "th": "khǎo mee phêuuan gee khon", "cat": "patterns", "script": "เขามีเพื่อนกี่คน"},
  {"en": "How many rooms does this house have?", "th": "bâan nêe mee gee hâwng", "cat": "patterns", "script": "บ้านนี้มีกี่ห้อง"},
  {"en": "How many bottles of beer did he drink?", "th": "khǎo dèum bia gee khùuad", "cat": "patterns", "script": "เขาดื่มเบียกี่ขวด"},
  {"en": "How many tickets will you buy?", "th": "khun jà sêuu dtǔua gee bai", "cat": "patterns", "script": "คุณจะซื้อตั๋วกี่ใบ"},
  {"en": "How many plates of rice do you want?", "th": "khun dtâwng-gaan khâao gee jaan", "cat": "patterns", "script": "คุณต้องการข้าวกี่จาน"},
  {"en": "now", "th": "dawn-nêe", "cat": "time", "script": "ดาวน์นี้"},
  {"en": "today", "th": "wan-nêe", "cat": "time", "script": "วันนี้"},
  {"en": "tomorrow", "th": "phrûng-nêe", "cat": "time", "script": "พรุ่งนี้"},
  {"en": "yesterday", "th": "mêuua-waan-nêe", "cat": "time", "script": "เมื่อวานนี้"},
  {"en": "the day before yesterday", "th": "mêuua-waan-seun", "cat": "time", "script": "เมื่อวานซืน"},
  {"en": "the day after tomorrow", "th": "bpee-nâa", "cat": "time", "script": "ปีหน้า"},
  {"en": "this week", "th": "aa-thíd-nêe", "cat": "time", "script": "อาทิตย์นี้"},
  {"en": "next week", "th": "aa-thíd-nâa", "cat": "time", "script": "อาทิตย์หน้า"},
  {"en": "last week", "th": "aa-thíd-thêe-lǎaeo", "cat": "time", "script": "อาทิตย์ที่แล้ว"},
  {"en": "this month", "th": "deuuan-nêe", "cat": "time", "script": "เดือนนี้"},
  {"en": "next month", "th": "deuuan-nâa", "cat": "time", "script": "เดือนหน้า"},
  {"en": "last month", "th": "deuuan-thêe-lǎaeo", "cat": "time", "script": "เดือนที่แล้ว"},
  {"en": "this year", "th": "bpee-nêe", "cat": "time", "script": "ปีนี้"},
  {"en": "next year", "th": "bpee-nâa", "cat": "time", "script": "ปีหน้า"},
  {"en": "last year", "th": "bpee-thêe-lǎaeo", "cat": "time", "script": "ปีที่แล้ว"},
  {"en": "day", "th": "wan", "cat": "time", "script": "วัน"},
  {"en": "week", "th": "aa-thíd", "cat": "time", "script": "อาทิตย์"},
  {"en": "month", "th": "deuuan", "cat": "time", "script": "เดือน"},
  {"en": "year", "th": "bpee", "cat": "time", "script": "ปี"},
  {"en": "next (modifier)", "th": "nâa", "cat": "time", "script": "หน้า", "note": "follows time word"},
  {"en": "last/ago/previous (modifier)", "th": "thêe-lǎaeo", "cat": "time", "script": "ที่แล้ว", "note": "follows time word"},
  {"en": "within", "th": "nai", "cat": "time", "script": "ใน"},
  {"en": "more", "th": "èek", "cat": "time", "script": "อีก"},
  {"en": "within (phǎai-nai)", "th": "phǎai-nai", "cat": "time", "script": "ภายใน"},
  {"en": "morning", "th": "dawn-cháo", "cat": "time", "script": "ดาวน์เช้า"},
  {"en": "midday", "th": "glaang-wan", "cat": "time", "script": "กลางวัน"},
  {"en": "afternoon (1pm-5pm)", "th": "dawn-bàai", "cat": "time", "script": "ดาวน์บ่าย"},
  {"en": "afternoon (5pm-9pm)", "th": "dawn-yen", "cat": "time", "script": "ดาวน์เย็น"},
  {"en": "evening", "th": "dawn-khâam", "cat": "time", "script": "ดาวน์ค่ำ"},
  {"en": "night", "th": "dawn-dtuun", "cat": "time", "script": "ดาวน์ดึก"},
  {"en": "this morning", "th": "dawn-cháo-nêe", "cat": "time", "script": "ดาวน์เช้านี้"},
  {"en": "this evening", "th": "dawn-yen-nêe", "cat": "time", "script": "ดาวน์เย็นนี้"},
  {"en": "this afternoon", "th": "dawn-bàai-nêe", "cat": "time", "script": "ดาวน์บ่ายนี้"},
  {"en": "tonight", "th": "kheuun-nêe", "cat": "time", "script": "คืนนี้"},
  {"en": "breakfast", "th": "aa-hǎan-cháo", "cat": "time", "script": "อาหารเช้า"},
  {"en": "lunch", "th": "aa-hǎan glaang-wan", "cat": "time", "script": "อาหารกลางวัน"},
  {"en": "dinner", "th": "aa-hǎan-yen", "cat": "time", "script": "อาหารเย็น"},
  {"en": "snack", "th": "aa-hǎan-wâang", "cat": "time", "script": "อาหารว่าง"},
  {"en": "to eat, to dine", "th": "gin aa-hǎan, thaan aa-hǎan", "cat": "time", "script": "กินอาหาร, ทานอาหาร"},
  {"en": "when?", "th": "mêuua-rài", "cat": "questions", "script": "เมื่อไร", "note": "usually at end of sentence"},
  {"en": "what?", "th": "à-rai", "cat": "questions", "script": "อะไร", "note": "usually at end of sentence"},
  {"en": "why?", "th": "tham-mai", "cat": "questions", "script": "ทำไม", "note": "usually at beginning"},
  {"en": "how?", "th": "yaang-rài", "cat": "questions", "script": "อย่างไร", "note": "usually at end of sentence"},
  {"en": "who?", "th": "khrai", "cat": "questions", "script": "ใคร", "note": "usually at end of sentence"},
  {"en": "where?", "th": "thêe-nǎi", "cat": "questions", "script": "ที่ไหน", "note": "usually at end of sentence"},
  {"en": "how many?", "th": "gee", "cat": "questions", "script": "กี่", "note": "before classifier"},
  {"en": "how much?", "th": "thâo-rài", "cat": "questions", "script": "เท่าไร", "note": "usually at end of sentence"},
  {"en": "When will you go to Bangkok?", "th": "khun jà bpai grung-thâep mêuua-rài", "cat": "questions", "script": "คุณจะไปกรุงเทพเมื่อไร"},
  {"en": "When did she come (arrive)?", "th": "ther maa mêuua-rài", "cat": "questions", "script": "เธอมาเมื่อไร"},
  {"en": "What are you doing?", "th": "khun tham à-rai", "cat": "questions", "script": "คุณทำอะไร"},
  {"en": "What is she doing here?", "th": "ther tham à-rai thêe-nêe", "cat": "questions", "script": "เธอทำอะไรที่นี่"},
  {"en": "What did you say?", "th": "khun phûud à-rai", "cat": "questions", "script": "คุณพูดอะไร"},
  {"en": "Why are you sitting here?", "th": "tham-mai khun nâng thêe-nêe", "cat": "questions", "script": "ทำไมคุณนั่งที่นี่"},
  {"en": "Why did she come yesterday?", "th": "tham-mai ther maa mêuua-waan-nêe", "cat": "questions", "script": "ทำไมเธอมาเมื่อวานนี้"},
  {"en": "How will you go to Bangkok?", "th": "khun jà bpai grung-thâep yaang-rài", "cat": "questions", "script": "คุณจะไปกรุงเทพอย่างไร"},
  {"en": "How can you eat that?", "th": "khun gin nân dâi yaang-rài", "cat": "questions", "script": "คุณกินนั่นได้อย่างไร"},
  {"en": "How can you remember?", "th": "khun jam dâi yaang-rài", "cat": "questions", "script": "คุณจำได้อย่างไร"},
  {"en": "come", "th": "maa", "cat": "verbs", "script": "มา"},
  {"en": "go", "th": "bpai", "cat": "verbs", "script": "ไป"},
  {"en": "eat", "th": "gin", "cat": "verbs", "script": "กิน"},
  {"en": "drink", "th": "dèum", "cat": "verbs", "script": "ดื่ม"},
  {"en": "work", "th": "tham-ngaan", "cat": "verbs", "script": "ทำงาน"},
  {"en": "do / make", "th": "tham", "cat": "verbs", "script": "ทำ"},
  {"en": "sit", "th": "nâng", "cat": "verbs", "script": "นั่ง"},
  {"en": "sleep", "th": "nawn", "cat": "verbs", "script": "นอน"},
  {"en": "look / watch", "th": "duu", "cat": "verbs", "script": "ดู"},
  {"en": "listen / hear", "th": "fang", "cat": "verbs", "script": "ฟัง"},
  {"en": "speak", "th": "phûud", "cat": "verbs", "script": "พูด"},
  {"en": "write", "th": "khǐan", "cat": "verbs", "script": "เขียน"},
  {"en": "read", "th": "àan", "cat": "verbs", "script": "อ่าน"},
  {"en": "think", "th": "khíd", "cat": "verbs", "script": "คิด"},
  {"en": "know (a person/place)", "th": "rúu-jàk", "cat": "verbs", "script": "รู้จัก"},
  {"en": "know (fact/info)", "th": "rúu", "cat": "verbs", "script": "รู้"},
  {"en": "understand", "th": "khâo-jai", "cat": "verbs", "script": "เข้าใจ"},
  {"en": "like", "th": "châwp", "cat": "verbs", "script": "ชอบ"},
  {"en": "love", "th": "rák", "cat": "verbs", "script": "รัก"},
  {"en": "remember", "th": "jam", "cat": "verbs", "script": "จำ"},
  {"en": "see", "th": "hěn", "cat": "verbs", "script": "เห็น"},
  {"en": "hear", "th": "dâi-yin", "cat": "verbs", "script": "ได้ยิน"},
  {"en": "call (phone)", "th": "thoo-hǎa", "cat": "verbs", "script": "โทรหา"},
  {"en": "wait", "th": "raw", "cat": "verbs", "script": "รอ"},
  {"en": "swim", "th": "wâai-nám", "cat": "verbs", "script": "ว่ายน้ำ"},
  {"en": "run", "th": "wîng", "cat": "verbs", "script": "วิ่ง"},
  {"en": "fly", "th": "bin", "cat": "verbs", "script": "บิน"},
  {"en": "walk", "th": "dèun", "cat": "verbs", "script": "เดิน"},
  {"en": "drive (car)", "th": "khàp ród-yon", "cat": "verbs", "script": "ขับรถยนต์"},
  {"en": "ride (motorcycle)", "th": "khèe rót-maw-ther-sai", "cat": "verbs", "script": "ขี่รถมอเตอร์ไซ"},
  {"en": "ride (a vehicle)", "th": "jú (sǔuad)", "cat": "verbs", "script": "จู้ (สวด)"},
  {"en": "take a train", "th": "nâng ród-fai", "cat": "verbs", "script": "นั่งรถไฟ"},
  {"en": "want to", "th": "dtâwng-gaan", "cat": "verbs", "script": "ต้องการ"},
  {"en": "would like to / just want", "th": "yàak (jà) / yàak-jà", "cat": "verbs", "script": "อยาก (จะ) / อยากจะ"},
  {"en": "Sunday", "th": "wan-aa-thíd", "cat": "days", "script": "วันอาทิตย์"},
  {"en": "Monday", "th": "wan-jan", "cat": "days", "script": "วันจันทร์"},
  {"en": "Tuesday", "th": "wan-ang-khaan", "cat": "days", "script": "วันอังคาร"},
  {"en": "Wednesday", "th": "wan-phúd", "cat": "days", "script": "วันพุธ"},
  {"en": "Thursday", "th": "wan-phá-rèu-hàd", "cat": "days", "script": "วันพฤหัสบดี"},
  {"en": "Friday", "th": "wan-sùk", "cat": "days", "script": "วันศุกร์"},
  {"en": "Saturday", "th": "wan-sǎo", "cat": "days", "script": "วันเสาร์"},
  {"en": "big / large", "th": "yài", "cat": "adjectives", "script": "ใหญ่"},
  {"en": "small", "th": "lék", "cat": "adjectives", "script": "เล็ก"},
  {"en": "open / on", "th": "bpèrd", "cat": "adjectives", "script": "เปิด"},
  {"en": "shut / closed / off", "th": "bpìd", "cat": "adjectives", "script": "ปิด"},
  {"en": "clean", "th": "sa-àad", "cat": "adjectives", "script": "สะอาด"},
  {"en": "dirty", "th": "sók-ga-bpròk", "cat": "adjectives", "script": "สกปรก"},
  {"en": "wide", "th": "gwâang", "cat": "adjectives", "script": "กว้าง"},
  {"en": "narrow", "th": "khâaep", "cat": "adjectives", "script": "แคบ"},
  {"en": "long", "th": "yaao", "cat": "adjectives", "script": "ยาว"},
  {"en": "short (height)", "th": "sân", "cat": "adjectives", "script": "สั้น"},
  {"en": "high / tall", "th": "sǔung", "cat": "adjectives", "script": "สูง"},
  {"en": "light weight", "th": "bao", "cat": "adjectives", "script": "เบา"},
  {"en": "heavy weight", "th": "nàk", "cat": "adjectives", "script": "หนัก"},
  {"en": "full", "th": "dtem", "cat": "adjectives", "script": "เต็ม"},
  {"en": "empty", "th": "bplàao", "cat": "adjectives", "script": "เปล่า"},
  {"en": "sharp (pointed)", "th": "làem", "cat": "adjectives", "script": "แหลม"},
  {"en": "sharp (blade)", "th": "khom", "cat": "adjectives", "script": "คม"},
  {"en": "new", "th": "mài", "cat": "adjectives", "script": "ใหม่"},
  {"en": "old (object)", "th": "gào", "cat": "adjectives", "script": "เก่า"},
  {"en": "old (person/animal)", "th": "gàae", "cat": "adjectives", "script": "แก่"},
  {"en": "hot", "th": "ráwn", "cat": "adjectives", "script": "ร้อน"},
  {"en": "cold (objects)", "th": "yen", "cat": "adjectives", "script": "เย็น"},
  {"en": "warm / to warm", "th": "ùn", "cat": "adjectives", "script": "อุ่น"},
  {"en": "low (height)", "th": "dtìa", "cat": "adjectives", "script": "เตี้ย"},
  {"en": "colour", "th": "sǐi", "cat": "adjectives", "script": "สี"},
  {"en": "white", "th": "sǐi-khǎao", "cat": "adjectives", "script": "สีขาว"},
  {"en": "black", "th": "sǐi-dam", "cat": "adjectives", "script": "สีดำ"},
  {"en": "red", "th": "sǐi-daaeng", "cat": "adjectives", "script": "สีแดง"},
  {"en": "yellow", "th": "sǐi-lêuang", "cat": "adjectives", "script": "สีเหลือง"},
  {"en": "green", "th": "sǐi-khǐaao", "cat": "adjectives", "script": "สีเขียว"},
  {"en": "grey", "th": "sǐi-thao", "cat": "adjectives", "script": "สีเทา"},
  {"en": "light blue", "th": "sǐi-fáa", "cat": "adjectives", "script": "สีฟ้า"},
  {"en": "dark blue", "th": "sǐi-nám-ngern", "cat": "adjectives", "script": "สีน้ำเงิน"},
  {"en": "see", "th": "hěn", "cat": "adjectives", "script": "เห็น"},
  {"en": "think", "th": "khíd", "cat": "adjectives", "script": "คิด"},
  {"en": "lay down", "th": "nawn", "cat": "adjectives", "script": "นอน"},
  {"en": "sleep", "th": "nawn-láp", "cat": "adjectives", "script": "นอนหลับ"},
  {"en": "7-11 / convenience store", "th": "sae-wên", "cat": "places", "script": "เซเว่น"},
  {"en": "bank", "th": "thá-naa-khaan", "cat": "places", "script": "ธนาคาร"},
  {"en": "shop", "th": "raan", "cat": "places", "script": "ร้าน"},
  {"en": "school", "th": "roong-riian", "cat": "places", "script": "โรงเรียน"},
  {"en": "restaurant", "th": "raan-aa-hǎan", "cat": "places", "script": "ร้านอาหาร"},
  {"en": "village", "th": "muu-bâan", "cat": "places", "script": "หมู่บ้าน"},
  {"en": "police station", "th": "sa-thǎa-nee dtam-rùuad", "cat": "places", "script": "สถานีตำรวจ"},
  {"en": "railway station", "th": "sa-thǎa-nee ród-fai", "cat": "places", "script": "สถานีรถไฟ"},
  {"en": "bar", "th": "baa", "cat": "places", "script": "บาร์"},
  {"en": "hotel", "th": "roong-raaem", "cat": "places", "script": "โรงแรม"},
  {"en": "cinema", "th": "roong-nâng", "cat": "places", "script": "โรงหนัง"},
  {"en": "market", "th": "dta-làad", "cat": "places", "script": "ตลาด"},
  {"en": "post office", "th": "bprai-sa-nee", "cat": "places", "script": "ไปรษณีย์"},
  {"en": "hospital", "th": "roong-pha-yaa-baan", "cat": "places", "script": "โรงพยาบาล"},
  {"en": "coffee shop", "th": "raan-gaa-faae", "cat": "places", "script": "ร้านกาแฟ"},
  {"en": "embassy", "th": "sa-thǎan-thûud", "cat": "places", "script": "สถานทูต"},
  {"en": "house / home", "th": "bâan", "cat": "places", "script": "บ้าน"},
  {"en": "district office", "th": "am-pher", "cat": "places", "script": "อำเภอ"},
  {"en": "airport", "th": "sa-nǎam-bin", "cat": "places", "script": "สนามบิน"},
  {"en": "Central (dept store)", "th": "sen-thran", "cat": "places", "script": "เซ็นทรัล"},
  {"en": "Jungceylon", "th": "Jang-see-lawn", "cat": "places", "script": "จังซีลอน"},
  {"en": "chair", "th": "gâo-êe", "cat": "nouns", "script": "เก้าอี้", "note": "furniture"},
  {"en": "table", "th": "dtoe", "cat": "nouns", "script": "โต๊ะ", "note": "furniture"},
  {"en": "sofa", "th": "soo-faa", "cat": "nouns", "script": "โซฟา", "note": "furniture"},
  {"en": "fridge", "th": "dtûu-yen", "cat": "nouns", "script": "ตู้เย็น", "note": "furniture"},
  {"en": "wardrobe / closet", "th": "dtûu-sêua-phâa", "cat": "nouns", "script": "ตู้เสื้อผ้า", "note": "furniture"},
  {"en": "plate", "th": "jaan", "cat": "nouns", "script": "จาน", "note": "food & drink"},
  {"en": "glass", "th": "gâaeo", "cat": "nouns", "script": "แก้ว", "note": "food & drink"},
  {"en": "spoon", "th": "châwn", "cat": "nouns", "script": "ช้อน", "note": "food & drink"},
  {"en": "fork", "th": "sâwm", "cat": "nouns", "script": "ส้อม", "note": "food & drink"},
  {"en": "knife", "th": "mêed", "cat": "nouns", "script": "มีด", "note": "food & drink"},
  {"en": "kettle", "th": "gaa-dtôm-nám-ráwn", "cat": "nouns", "script": "กาต้มน้ำร้อน", "note": "food & drink"},
  {"en": "cup", "th": "thûuai", "cat": "nouns", "script": "ถ้วย", "note": "food & drink"},
  {"en": "food", "th": "a-hǎan", "cat": "nouns", "script": "อาหาร", "note": "food & drink"},
  {"en": "microwave", "th": "mai-kroo-wáep", "cat": "nouns", "script": "ไมโครเวฟ", "note": "food & drink"},
  {"en": "water", "th": "nám", "cat": "nouns", "script": "น้ำ", "note": "food & drink"},
  {"en": "swim", "th": "sâawm", "cat": "nouns", "script": "ว่ายน้ำ", "note": "food & drink"},
  {"en": "shirt / blouse", "th": "sêua", "cat": "nouns", "script": "เสื้อ", "note": "clothing"},
  {"en": "T-shirt", "th": "sêua-yéuud", "cat": "nouns", "script": "เสื้อยืด", "note": "clothing"},
  {"en": "handbag", "th": "grà-bpǎo", "cat": "nouns", "script": "กระเป๋า", "note": "clothing"},
  {"en": "skirt", "th": "nsìt", "cat": "nouns", "script": "กระโปรง", "note": "clothing"},
  {"en": "shorts", "th": "gaeng-gaeng-khâa-sân", "cat": "nouns", "script": "กางเกงขาสั้น", "note": "clothing"},
  {"en": "denim jeans", "th": "gaeng-gaeng-yeen", "cat": "nouns", "script": "กางเกงยีนส์", "note": "clothing"},
  {"en": "hat", "th": "mùuak", "cat": "nouns", "script": "หมวก", "note": "clothing"},
  {"en": "umbrella", "th": "rôm", "cat": "nouns", "script": "ร่ม", "note": "clothing"},
  {"en": "smartphone", "th": "meu-thêuu", "cat": "nouns", "script": "มือถือ", "note": "technology"},
  {"en": "notebook", "th": "nóed-buk", "cat": "nouns", "script": "โน้ตบุ๊ก", "note": "technology"},
  {"en": "fan", "th": "phâd-lom", "cat": "nouns", "script": "พัดลม", "note": "technology"},
  {"en": "TV", "th": "thee-wee", "cat": "nouns", "script": "ทีวี", "note": "technology"},
  {"en": "computer", "th": "khawm-pîw-dtêr", "cat": "nouns", "script": "คอมพิวเตอร์", "note": "technology"},
  {"en": "remote control", "th": "ree-moed", "cat": "nouns", "script": "รีโมด", "note": "technology"},
  {"en": "tablet", "th": "thǎaep-lèd", "cat": "nouns", "script": "แท็บเล็ต", "note": "technology"},
  {"en": "air-con", "th": "aae", "cat": "nouns", "script": "แอร์", "note": "technology"},
  {"en": "door", "th": "bprà-dtuu", "cat": "nouns", "script": "ประตู", "note": "miscellaneous"},
  {"en": "window", "th": "nâa-dtaang", "cat": "nouns", "script": "หน้าต่าง", "note": "miscellaneous"},
  {"en": "Basic sentence", "th": "Subject + Verb  e.g. phǒm bpai (I go)", "cat": "grammar", "note": "No conjugation needed"},
  {"en": "Tense (context)", "th": "Same verb form for all tenses", "cat": "grammar", "note": "Context or time word clarifies tense"},
  {"en": "Future tense", "th": "Subject + jà + Verb  e.g. phǒm jà bpai", "cat": "grammar", "note": "jà signals future intention"},
  {"en": "Negative", "th": "Subject + mâi + Verb  e.g. phǒm mâi bpai", "cat": "grammar", "note": "mâi = no/not"},
  {"en": "Negative (want/would like)", "th": "Subject + mâi + dtâwng-gaan / yàak-jà + Verb", "cat": "grammar"},
  {"en": "Question", "th": "Positive statement + mǎi at end", "cat": "grammar", "note": "Sentence-final mǎi creates yes/no question"},
  {"en": "Here", "th": "thêe-nêe", "cat": "grammar", "note": "place adverb follows verb"},
  {"en": "There", "th": "thêe-nân", "cat": "grammar", "note": "place adverb follows verb"},
  {"en": "Come here", "th": "maa thêe-nêe", "cat": "grammar", "note": "maa = coming toward speaker"},
  {"en": "Go there", "th": "bpai thêe-nân", "cat": "grammar", "note": "bpai = moving away from speaker"},
  {"en": "With (conjunction)", "th": "Subject + Verb + gàp + Person", "cat": "grammar", "note": "e.g. phǒm bpai gàp khun"},
  {"en": "And (conjunction)", "th": "lɛ́ (lae)", "cat": "grammar", "note": "e.g. knife lɛ́ fork"},
  {"en": "Polite particle (male)", "th": "khráp – add to end of sentence", "cat": "grammar"},
  {"en": "Polite particle (female)", "th": "khà – add to end of sentence", "cat": "grammar"},
  {"en": "Want to", "th": "dtâwng-gaan + Verb", "cat": "grammar", "note": "formal / stronger"},
  {"en": "Would like to", "th": "yàak (jà) + Verb", "cat": "grammar", "note": "yàak or yàak-jà"},
  {"en": "Travelling verb (away)", "th": "bpai follows main verb", "cat": "grammar", "note": "e.g. khàp ród bpai Phuket"},
  {"en": "Travelling verb (toward)", "th": "maa follows main verb", "cat": "grammar", "note": "e.g. khun maa thêe-nêe"},
  {"en": "Math: add", "th": "bùuak", "cat": "grammar"},
  {"en": "Math: subtract", "th": "lóp", "cat": "grammar"},
  {"en": "Math: multiply", "th": "khùun", "cat": "grammar"},
  {"en": "Math: divide", "th": "hàan (dûuai)", "cat": "grammar"},
  {"en": "Math: equals", "th": "thâo-gàp", "cat": "grammar"},
  {"en": "Answering yes/no questions", "th": "Repeat the verb on its own", "cat": "grammar", "note": "e.g. bpai? → bpai (yes) / mâi bpai (no)"},
  {"en": "Answering mâi questions (negative)", "th": "Use verb alone (yes) or mâi + verb (no)", "cat": "grammar", "note": "Same pattern"},
  {"en": "Short question form", "th": "Drop khun, use verb + mǎi directly", "cat": "grammar", "note": "When speaking to someone directly"},
  {"en": "Can / ability", "th": "Subject + Verb + dâi", "cat": "grammar", "note": "dâi always at end of sentence"},
  {"en": "Cannot", "th": "Subject + Verb + mâi-dâi", "cat": "grammar", "note": "mâi placed in front of dâi"},
  {"en": "Can? question", "th": "Subject + Verb + dâi mǎi", "cat": "grammar", "note": "dâi mǎi at end"},
  {"en": "Answer can? yes", "th": "dâi / lôe (informal)", "cat": "grammar"},
  {"en": "Answer can? no", "th": "mâi-dâi", "cat": "grammar"},
  {"en": "Literal/compound verbs", "th": "Pair of verbs with literal + actual meaning", "cat": "grammar", "note": "e.g. nawn-láp = sleep (lay down + sleep)"},
  {"en": "Irregular dâi verbs", "th": "nawn-láp, mawng-hěn, khíd-àwk", "cat": "grammar", "note": "cannot → nawn mâi láp, mawng mâi hěn, khíd mâi àwk"},
  {"en": "Verb-to-be 1 (bpen)", "th": "Used with objects (everything except people)", "cat": "grammar", "note": "nân bpen dtoe = That is a table"},
  {"en": "Verb-to-be 1 negative", "th": "mâi châi", "cat": "grammar", "note": "nân mâi châi dtoe = That is not a table"},
  {"en": "Verb-to-be 2 (kheuu)", "th": "Used exclusively with people", "cat": "grammar", "note": "nân kheuu John = That is John"},
  {"en": "Verb-to-be 2 negative", "th": "mâi châi", "cat": "grammar", "note": "nân mâi châi Jane = That is not Jane"},
  {"en": "Verb-to-be 3 (yùu)", "th": "Used exclusively with location", "cat": "grammar", "note": "khǎo yùu thêe-nêe = He is here"},
  {"en": "Verb-to-be 3 negative", "th": "mâi yùu", "cat": "grammar", "note": "khǎo mâi yùu thêe-nêe = He is not here"},
  {"en": "This (singular)", "th": "nêe", "cat": "grammar", "note": "นี่"},
  {"en": "These (plural)", "th": "nêe", "cat": "grammar", "note": "นี่"},
  {"en": "That (singular)", "th": "nân", "cat": "grammar", "note": "นั่น"},
  {"en": "Those (plural)", "th": "nân", "cat": "grammar", "note": "นั่น"},
  {"en": "Where (thêe-nǎi)", "th": "Comes at end of sentence with yùu", "cat": "grammar", "note": "khǎo yùu thêe-nǎi = Where is he?"},
  {"en": "Where in can? question", "th": "Always ends with dâi", "cat": "grammar", "note": "bpai thêe-nǎi dâi = Where can we go?"},
  {"en": "Who (khrai)", "th": "Mostly at end of sentence", "cat": "grammar", "note": "phûud gàp khrai = Who are you speaking with?"},
  {"en": "Whose (khâwng-khrai)", "th": "After noun to query ownership", "cat": "grammar", "note": "nêe bpen grà-bpǎo khâwng-khrai = Whose handbag is this?"},
  {"en": "Possessive adjective", "th": "khâwng + pronoun before noun", "cat": "grammar", "note": "khâwng-phǒm = my/mine"},
  {"en": "my / mine", "th": "khâwng-phǒm / khâwng-chǎn", "cat": "grammar", "note": "ของผม / ของฉัน"},
  {"en": "your / yours", "th": "khâwng-khun", "cat": "grammar", "note": "ของคุณ"},
  {"en": "his", "th": "khâwng-khǎo", "cat": "grammar", "note": "ของเขา"},
  {"en": "her / hers", "th": "khâwng-ther", "cat": "grammar", "note": "ของเธอ"},
  {"en": "our / ours", "th": "khâwng-phûuak-rao", "cat": "grammar", "note": "ของพวกเรา"},
  {"en": "their / theirs", "th": "khâwng-phûuak-khǎo", "cat": "grammar", "note": "ของพวกเขา"},
  {"en": "its", "th": "khâwng-man", "cat": "grammar", "note": "ของมัน"},
  {"en": "Peter's", "th": "khâwng-Peter", "cat": "grammar", "note": "ของปีเตอร์"},

  {"en":"red","th":"sii daeng","cat":"colors","script":"สีแดง"},
  {"en":"blue","th":"sii fah","cat":"colors","script":"สีฟ้า"},
  {"en":"green","th":"sii khiao","cat":"colors","script":"สีเขียว"},
  {"en":"yellow","th":"sii leuang","cat":"colors","script":"สีเหลือง"},
  {"en":"black","th":"sii dam","cat":"colors","script":"สีดำ"},
  {"en":"white","th":"sii khao","cat":"colors","script":"สีขาว"},
  {"en":"pink","th":"sii chompoo","cat":"colors","script":"สีชมพู"},
  {"en":"orange","th":"sii som","cat":"colors","script":"สีส้ม"},
  {"en":"purple","th":"sii muang","cat":"colors","script":"สีม่วง"},
  {"en":"brown","th":"sii nam tan","cat":"colors","script":"สีน้ำตาล"},
  {"en":"grey","th":"sii thao","cat":"colors","script":"สีเทา"},
  {"en":"gold","th":"sii thong","cat":"colors","script":"สีทอง"},
  {"en":"father","th":"pho","cat":"family","script":"พ่อ"},
  {"en":"mother","th":"mae","cat":"family","script":"แม่"},
  {"en":"older sibling","th":"phi","cat":"family","script":"พี่"},
  {"en":"younger sibling","th":"nong","cat":"family","script":"น้อง"},
  {"en":"husband","th":"pua","cat":"family","script":"ผัว"},
  {"en":"wife","th":"mia","cat":"family","script":"เมีย"},
  {"en":"son","th":"luk chai","cat":"family","script":"ลูกชาย"},
  {"en":"daughter","th":"luk sao","cat":"family","script":"ลูกสาว"},
  {"en":"grandfather","th":"poo / ta","cat":"family","script":"ปู่ / ตา"},
  {"en":"grandmother","th":"ya / yai","cat":"family","script":"ย่า / ยาย"},
  {"en":"uncle","th":"lung / na","cat":"family","script":"ลุง / น้า"},
  {"en":"aunt","th":"pa / na","cat":"family","script":"ป้า / น้า"},
  {"en":"friend","th":"pheuan","cat":"family","script":"เพื่อน"},
  {"en":"neighbor","th":"pheuan ban","cat":"family","script":"เพื่อนบ้าน"},
  {"en":"child","th":"dek / luk","cat":"family","script":"เด็ก / ลูก"},
  {"en":"dog","th":"maa (falling tone)","cat":"animals","script":"หมา","note":"falling tone; same syllable as horse (rising) and come (mid)"},
  {"en":"cat","th":"maew","cat":"animals","script":"แมว"},
  {"en":"elephant","th":"chang","cat":"animals","script":"ช้าง","note":"classifier for elephants; chang also means 'carpenter'"},
  {"en":"monkey","th":"ling","cat":"animals","script":"ลิง"},
  {"en":"bird","th":"nok","cat":"animals","script":"นก","note":"classifier for birds; also means 'outside' in some contexts"},
  {"en":"snake","th":"ngu","cat":"animals","script":"งู"},
  {"en":"tiger","th":"seua","cat":"animals","script":"เสือ","note":"same romanization as shirt (seua) — tones differ"},
  {"en":"horse","th":"maa (rising tone)","cat":"animals","script":"ม้า","note":"rising tone; same syllable as dog (falling) and come (mid)"},
  {"en":"cow","th":"wua","cat":"animals","script":"วัว","note":"classifier for cattle"},
  {"en":"pig","th":"moo","cat":"animals","script":"หมู","note":"also means pork (food); same word"},
  {"en":"duck","th":"pet","cat":"animals","script":"เป็ด","note":"same romanization as spicy (pet) — tones differ"},
  {"en":"rabbit","th":"gra-tai","cat":"animals","script":"กระต่าย"},
  {"en":"frog","th":"gob","cat":"animals","script":"กบ"},
  {"en":"mosquito","th":"yung","cat":"animals","script":"ยุง"},
  {"en":"ant","th":"mot","cat":"animals","script":"มด"},
  {"en":"butterfly","th":"phi seua","cat":"animals","script":"ผีเสื้อ"},
  {"en":"crocodile","th":"jaw-ra-khe","cat":"animals","script":"จระเข้"},
  {"en":"fish","th":"pla","cat":"animals","script":"ปลา","note":"same word as fish (food)"},
  {"en":"chicken (animal)","th":"gai","cat":"animals","script":"ไก่","note":"same word as chicken (food); also classifier for chickens"},
  {"en":"buffalo","th":"khwai","cat":"animals","script":"ควาย"},
  {"en":"car","th":"rot","cat":"transport","script":"รถ"},
  {"en":"motorbike","th":"rot mor-ter-sai","cat":"transport","script":"รถมอเตอร์ไซค์"},
  {"en":"bus","th":"rot may","cat":"transport","script":"รถเมล์"},
  {"en":"train","th":"rot fai","cat":"transport","script":"รถไฟ"},
  {"en":"taxi","th":"taxi","cat":"transport","script":"แท็กซี่"},
  {"en":"tuk-tuk","th":"tuk-tuk","cat":"transport","script":"ตุ๊กตุ๊ก"},
  {"en":"boat","th":"reua","cat":"transport","script":"เรือ"},
  {"en":"plane","th":"khreuang bin","cat":"transport","script":"เครื่องบิน"},
  {"en":"bicycle","th":"rot jak-gra-yaan","cat":"transport","script":"รถจักรยาน"},
  {"en":"subway / MRT","th":"rot fai tai din","cat":"transport","script":"รถไฟใต้ดิน"},
  {"en":"ticket","th":"tua","cat":"transport","script":"ตั๋ว"},
  {"en":"road / street","th":"thanon","cat":"transport","script":"ถนน"},
  {"en":"happy","th":"dee jai","cat":"emotions","script":"ดีใจ"},
  {"en":"sad","th":"sia jai","cat":"emotions","script":"เสียใจ"},
  {"en":"angry","th":"grot","cat":"emotions","script":"โกรธ"},
  {"en":"scared","th":"glua","cat":"emotions","script":"กลัว"},
  {"en":"lonely","th":"ngao","cat":"emotions","script":"เหงา"},
  {"en":"stressed","th":"khriat","cat":"emotions","script":"เครียด"},
  {"en":"relaxed","th":"sa-bai jai","cat":"emotions","script":"สบายใจ"},
  {"en":"proud","th":"pa-oom jai","cat":"emotions","script":"ภูมิใจ"},
  {"en":"embarrassed","th":"a-y","cat":"emotions","script":"อาย"},
  {"en":"jealous","th":"it-cha","cat":"emotions","script":"อิจฉา"},
  {"en":"confused","th":"ngong","cat":"emotions","script":"งง"},
  {"en":"excited","th":"teun ten","cat":"emotions","script":"ตื่นเต้น"},
  {"en":"nervous","th":"neua non mai yu","cat":"emotions","script":"เนื้อนอนไม่หลับ"},
  {"en":"grateful","th":"kob jai","cat":"emotions","script":"ขอบใจ"},
  {"en":"bored","th":"beua","cat":"emotions","script":"เบื่อ"},

  {"en":"delicious","th":"aroy","cat":"food","script":"อร่อย"},
  {"en":"spicy","th":"pet","cat":"food","script":"เผ็ด","note":"same romanization as 'duck' (pet) — tone differs"},
  {"en":"not spicy","th":"mai pet","cat":"food","script":"ไม่เผ็ด"},
  {"en":"sweet","th":"wan","cat":"food","script":"หวาน"},
  {"en":"sour","th":"priao","cat":"food","script":"เปรี้ยว"},
  {"en":"salty","th":"khem","cat":"food","script":"เค็ม"},
  {"en":"bitter","th":"khom","cat":"food","script":"ขม"},
  {"en":"rice","th":"khao","cat":"food","script":"ข้าว","note":"also: white (color), enter (verb) — tones differ"},
  {"en":"sticky rice","th":"khao niao","cat":"food","script":"ข้าวเหนียว"},
  {"en":"fried rice","th":"khao pad","cat":"food","script":"ข้าวผัด"},
  {"en":"noodles","th":"gway teow","cat":"food","script":"ก๋วยเตี๋ยว"},
  {"en":"pad thai","th":"pad thai","cat":"food","script":"ผัดไทย"},
  {"en":"tom yum soup","th":"tom yum","cat":"food","script":"ต้มยำ"},
  {"en":"green curry","th":"gaeng khiao wan","cat":"food","script":"แกงเขียวหวาน"},
  {"en":"red curry","th":"gaeng daeng","cat":"food","script":"แกงแดง"},
  {"en":"papaya salad","th":"som tam","cat":"food","script":"ส้มตำ"},
  {"en":"mango sticky rice","th":"khao niao mamuang","cat":"food","script":"ข้าวเหนียวมะม่วง"},
  {"en":"spring rolls","th":"poh pia","cat":"food","script":"ปอเปี๊ยะ"},
  {"en":"satay","th":"satay","cat":"food","script":"สะเต๊ะ"},
  {"en":"chicken","th":"gai","cat":"food","script":"ไก่"},
  {"en":"pork","th":"moo","cat":"food","script":"หมู"},
  {"en":"beef","th":"nuea","cat":"food","script":"เนื้อ"},
  {"en":"fish","th":"pla","cat":"food","script":"ปลา"},
  {"en":"shrimp","th":"goong","cat":"food","script":"กุ้ง"},
  {"en":"crab","th":"poo","cat":"food","script":"ปู"},
  {"en":"squid","th":"pla muek","cat":"food","script":"ปลาหมึก"},
  {"en":"egg","th":"khai","cat":"food","script":"ไข่"},
  {"en":"tofu","th":"tao hoo","cat":"food","script":"เต้าหู้"},
  {"en":"vegetables","th":"phak","cat":"food","script":"ผัก"},
  {"en":"garlic","th":"gratiam","cat":"food","script":"กระเทียม"},
  {"en":"onion","th":"hua hom","cat":"food","script":"หัวหอม"},
  {"en":"chili","th":"phrik","cat":"food","script":"พริก"},
  {"en":"ginger","th":"khing","cat":"food","script":"ขิง"},
  {"en":"lemongrass","th":"ta krai","cat":"food","script":"ตะไคร้"},
  {"en":"coconut milk","th":"ga ti","cat":"food","script":"กะทิ"},
  {"en":"fish sauce","th":"nam pla","cat":"food","script":"น้ำปลา"},
  {"en":"soy sauce","th":"see-ew","cat":"food","script":"ซีอิ๊ว"},
  {"en":"sugar","th":"nam tan","cat":"food","script":"น้ำตาล","note":"literally 'palm water'; nam tan also = brown (sii nam tan)"},
  {"en":"salt","th":"gleua","cat":"food","script":"เกลือ"},
  {"en":"lime","th":"manao","cat":"food","script":"มะนาว"},
  {"en":"mango","th":"mamuang","cat":"food","script":"มะม่วง"},
  {"en":"banana","th":"gluai","cat":"food","script":"กล้วย"},
  {"en":"pineapple","th":"sapparot","cat":"food","script":"สับปะรด"},
  {"en":"watermelon","th":"taeng mo","cat":"food","script":"แตงโม"},
  {"en":"durian","th":"thurian","cat":"food","script":"ทุเรียน"},
  {"en":"coconut","th":"maprao","cat":"food","script":"มะพร้าว"},
  {"en":"bread","th":"khanom pang","cat":"food","script":"ขนมปัง"},
  {"en":"soup","th":"gaeng / tom","cat":"food","script":"แกง / ต้ม"},
  {"en":"stir-fried","th":"pad","cat":"food","script":"ผัด","note":"cooking method prefix, e.g. pad thai, pad kra pao"},
  {"en":"deep-fried","th":"thot","cat":"food","script":"ทอด"},
  {"en":"steamed","th":"neung","cat":"food","script":"นึ่ง","note":"same romanization as 'one' (neung) — tone differs"},
  {"en":"grilled","th":"ping / yang","cat":"food","script":"ปิ้ง / ย่าง"},
  {"en":"fried egg","th":"khai dao","cat":"food","script":"ไข่ดาว"},
  {"en":"omelette","th":"khai jeow","cat":"food","script":"ไข่เจียว"},
  {"en":"papaya","th":"malakaw","cat":"food","script":"มะละกอ"},
  {"en":"water","th":"nam","cat":"food","script":"น้ำ"},
  {"en":"coffee","th":"gafae","cat":"food","script":"กาแฟ"},
  {"en":"tea","th":"cha","cat":"food","script":"ชา"},
  {"en":"beer","th":"bia","cat":"food","script":"เบียร์"},
  {"en":"wine","th":"wayn","cat":"food","script":"ไวน์"},
  {"en":"juice","th":"nam phon lamai","cat":"food","script":"น้ำผลไม้"},
  {"en":"coconut water","th":"nam maprao","cat":"food","script":"น้ำมะพร้าว"},
  {"en":"soda","th":"nam at lom","cat":"food","script":"น้ำอัดลม"},
  {"en":"milk","th":"nom","cat":"food","script":"นม"},
  {"en":"ice","th":"nam khaeng","cat":"food","script":"น้ำแข็ง"},

  {"en":"head","th":"hua","cat":"body"},
  {"en":"face","th":"na","cat":"body"},
  {"en":"eye","th":"ta","cat":"body"},
  {"en":"ear","th":"hoo","cat":"body"},
  {"en":"nose","th":"jamook","cat":"body"},
  {"en":"mouth","th":"pak","cat":"body"},
  {"en":"tooth","th":"fan","cat":"body"},
  {"en":"hair","th":"phom","cat":"body"},
  {"en":"neck","th":"kor","cat":"body"},
  {"en":"shoulder","th":"lai","cat":"body"},
  {"en":"arm","th":"khaen","cat":"body"},
  {"en":"hand","th":"meu","cat":"body"},
  {"en":"finger","th":"niu","cat":"body"},
  {"en":"chest","th":"ok","cat":"body"},
  {"en":"stomach","th":"thong","cat":"body"},
  {"en":"back","th":"lang","cat":"body"},
  {"en":"leg","th":"kha","cat":"body"},
  {"en":"knee","th":"hua khao","cat":"body"},
  {"en":"foot","th":"tao","cat":"body"},
  {"en":"heart","th":"hua jai","cat":"body"},
  {"en":"shirt","th":"seua","cat":"clothing"},
  {"en":"trousers / pants","th":"gang-geng","cat":"clothing"},
  {"en":"dress","th":"seua phah","cat":"clothing"},
  {"en":"skirt","th":"gra-prong","cat":"clothing"},
  {"en":"shoes","th":"rong thao","cat":"clothing"},
  {"en":"sandals","th":"rong thao taem","cat":"clothing"},
  {"en":"hat","th":"muat","cat":"clothing"},
  {"en":"glasses","th":"waen ta","cat":"clothing"},
  {"en":"bag","th":"gra-pao","cat":"clothing"},
  {"en":"watch","th":"na li ga","cat":"clothing"},
  {"en":"ring","th":"waen","cat":"clothing"},
  {"en":"necklace","th":"soy kor","cat":"clothing"},
  {"en":"clothes","th":"seua pha","cat":"clothing"},
  {"en":"jacket / coat","th":"seua klum","cat":"clothing"},
  {"en":"underwear","th":"gang-geng nai","cat":"clothing"},
  {"en":"sun","th":"pra-a-tit","cat":"nature"},
  {"en":"moon","th":"pra-jan","cat":"nature"},
  {"en":"star","th":"dao","cat":"nature"},
  {"en":"sky","th":"fa","cat":"nature"},
  {"en":"cloud","th":"mek","cat":"nature"},
  {"en":"rain","th":"fon","cat":"nature"},
  {"en":"wind","th":"lom","cat":"nature"},
  {"en":"mountain","th":"phu-khao","cat":"nature"},
  {"en":"river","th":"mae-nam","cat":"nature"},
  {"en":"sea / ocean","th":"ta-le","cat":"nature"},
  {"en":"beach","th":"hat","cat":"nature"},
  {"en":"island","th":"ko","cat":"nature"},
  {"en":"tree","th":"ton mai","cat":"nature"},
  {"en":"flower","th":"dok mai","cat":"nature"},
  {"en":"grass","th":"ya","cat":"nature"},
  {"en":"hot (weather)","th":"rorn","cat":"weather"},
  {"en":"cold (weather)","th":"nao","cat":"weather"},
  {"en":"cool","th":"yen","cat":"weather"},
  {"en":"it's raining","th":"fon tok","cat":"weather"},
  {"en":"sunny","th":"daet ork","cat":"weather"},
  {"en":"cloudy","th":"fa mit","cat":"weather"},
  {"en":"windy","th":"lom paed","cat":"weather"},
  {"en":"humid","th":"cheun","cat":"weather"},
  {"en":"dry season","th":"na raeng","cat":"weather"},
  {"en":"rainy season","th":"na fon","cat":"weather"},
  {"en":"room","th":"hong","cat":"home"},
  {"en":"bedroom","th":"hong norn","cat":"home"},
  {"en":"bathroom","th":"hong nam","cat":"home"},
  {"en":"kitchen","th":"khrua","cat":"home"},
  {"en":"living room","th":"hong nang len","cat":"home"},
  {"en":"door","th":"pra-too","cat":"home"},
  {"en":"window","th":"na-tang","cat":"home"},
  {"en":"table","th":"toh","cat":"home"},
  {"en":"chair","th":"gao-ee","cat":"home"},
  {"en":"bed","th":"tiang","cat":"home"},
  {"en":"pillow","th":"morn","cat":"home"},
  {"en":"air conditioning","th":"ea","cat":"home"},
  {"en":"fan","th":"phat lom","cat":"home"},
  {"en":"television","th":"tho-ra-that","cat":"home"},
  {"en":"refrigerator","th":"too yen","cat":"home"},
  {"en":"January","th":"ma-ga-ra-khom","cat":"months"},
  {"en":"February","th":"gum-pha-phan","cat":"months"},
  {"en":"March","th":"mee-na-khom","cat":"months"},
  {"en":"April","th":"may-sa-yon","cat":"months"},
  {"en":"May","th":"phreut-sa-pha-khom","cat":"months"},
  {"en":"June","th":"mi-thu-na-yon","cat":"months"},
  {"en":"July","th":"ga-ra-ga-da-khom","cat":"months"},
  {"en":"August","th":"sing-ha-khom","cat":"months"},
  {"en":"September","th":"gan-ya-yon","cat":"months"},
  {"en":"October","th":"tu-la-khom","cat":"months"},
  {"en":"November","th":"phreut-sa-ji-ga-yon","cat":"months"},
  {"en":"December","th":"than-wa-khom","cat":"months"},
  {"en":"left","th":"sai","cat":"directions"},
  {"en":"right","th":"khwa","cat":"directions"},
  {"en":"straight ahead","th":"trong pai","cat":"directions"},
  {"en":"turn","th":"leo","cat":"directions"},
  {"en":"north","th":"nuea","cat":"directions"},
  {"en":"south","th":"tai","cat":"directions"},
  {"en":"east","th":"tawan ork","cat":"directions"},
  {"en":"west","th":"tawan tok","cat":"directions"},
  {"en":"near","th":"klai","cat":"directions"},
  {"en":"far","th":"glai","cat":"directions"},
  {"en":"doctor","th":"moh","cat":"health"},
  {"en":"nurse","th":"pha-ya-ban","cat":"health"},
  {"en":"medicine","th":"ya","cat":"health"},
  {"en":"sick / unwell","th":"mai sa-bai","cat":"health"},
  {"en":"hurt / pain","th":"jep","cat":"health"},
  {"en":"headache","th":"puad hua","cat":"health"},
  {"en":"stomach ache","th":"puad thong","cat":"health"},
  {"en":"fever","th":"pen khai","cat":"health"},
  {"en":"cold (illness)","th":"pen wat","cat":"health"},
  {"en":"cough","th":"ai","cat":"health"},
  {"en":"allergy","th":"phaeng","cat":"health"},
  {"en":"emergency","th":"chuak-chern","cat":"health"},
  {"en":"ambulance","th":"rot pha-ya-ban","cat":"health"},
  {"en":"blood","th":"leuad","cat":"health"},
  {"en":"dizzy","th":"wian hua","cat":"health"},
  {"en":"I feel unwell","th":"phom mai sa-bai","cat":"health"},
  {"en":"call a doctor","th":"riak moh","cat":"health"},
  {"en":"pharmacy","th":"raan khai ya","cat":"health"},
  {"en":"tired / exhausted","th":"neuy","cat":"health"},
  {"en":"broken / injured","th":"hak / bat jep","cat":"health"},
  {"en":"work","th":"tham ngan","cat":"work"},
  {"en":"job / career","th":"a-cheep","cat":"work"},
  {"en":"boss","th":"jao nai","cat":"work"},
  {"en":"colleague","th":"pheuan ruam ngan","cat":"work"},
  {"en":"meeting","th":"pra-chum","cat":"work"},
  {"en":"computer","th":"khom-phiu-ter","cat":"work"},
  {"en":"phone","th":"tho-ra-sap","cat":"work"},
  {"en":"email","th":"ee-mel","cat":"work"},
  {"en":"school","th":"rong rian","cat":"work"},
  {"en":"teacher","th":"khruu","cat":"work"},
  {"en":"student","th":"nak rian","cat":"work"},
  {"en":"homework","th":"gan ban","cat":"work"},
  {"en":"exam / test","th":"sob","cat":"work"},
  {"en":"pass","th":"phan","cat":"work"},
  {"en":"fail","th":"tok","cat":"work"},
  {"en":"salary","th":"ngoen deuan","cat":"work"},
  {"en":"holiday / day off","th":"wan yut","cat":"work"},
  {"en":"busy","th":"yung","cat":"work"},
  {"en":"free (not busy)","th":"wang","cat":"work"},
  {"en":"project","th":"krong-gaan","cat":"work"},
  {"en":"eat","th":"kin","cat":"verbs"},
  {"en":"drink","th":"deum","cat":"verbs"},
  {"en":"sleep","th":"norn","cat":"verbs"},
  {"en":"wake up","th":"teun","cat":"verbs"},
  {"en":"go","th":"pai","cat":"verbs"},
  {"en":"come","th":"ma","cat":"verbs","note":"mid tone; same syllable as dog (falling) and horse (rising)"},
  {"en":"want","th":"ao / yaak","cat":"verbs","note":"ao = colloquial 'want/take'; yaak = to want/wish (more formal)"},
  {"en":"don't want","th":"mai ao","cat":"verbs"},
  {"en":"like","th":"chob","cat":"verbs"},
  {"en":"love","th":"rak","cat":"verbs"},
  {"en":"hate","th":"gliat","cat":"verbs"},
  {"en":"see","th":"hen","cat":"verbs"},
  {"en":"look / watch","th":"doo","cat":"verbs"},
  {"en":"listen","th":"fang","cat":"verbs"},
  {"en":"speak / talk","th":"poot","cat":"verbs"},
  {"en":"read","th":"an","cat":"verbs"},
  {"en":"write","th":"khian","cat":"verbs"},
  {"en":"understand","th":"khao jai","cat":"verbs"},
  {"en":"know","th":"roo","cat":"verbs"},
  {"en":"think","th":"khit","cat":"verbs"},
  {"en":"forget","th":"leum","cat":"verbs"},
  {"en":"help","th":"chuay","cat":"verbs"},
  {"en":"buy","th":"seu","cat":"verbs"},
  {"en":"sell","th":"khai","cat":"verbs","note":"same romanization as egg (khai, food) — tones differ"},
  {"en":"pay","th":"jai ngoen","cat":"verbs"},
  {"en":"don't have","th":"mai mee","cat":"verbs"},
  {"en":"can","th":"dai","cat":"verbs","note":"also: past tense marker placed after verb; 'to get/obtain'"},
  {"en":"cannot","th":"mai dai","cat":"verbs","note":"mai = negation; dai = can; mai dai also = 'didn't' (past tense)"},
  {"en":"stay / live","th":"yoo","cat":"verbs"},
  {"en":"sit","th":"nang","cat":"verbs"},
  {"en":"stand","th":"yeun","cat":"verbs"},
  {"en":"walk","th":"dern","cat":"verbs"},
  {"en":"run","th":"wing","cat":"verbs"},
  {"en":"drive","th":"khap","cat":"verbs"},
  {"en":"ride (motorbike)","th":"khee","cat":"verbs"},
  {"en":"swim","th":"way nam","cat":"verbs"},
  {"en":"cook","th":"tam khrua","cat":"verbs"},
  {"en":"clean","th":"tham kwahm sa-aat","cat":"verbs"},
  {"en":"wash","th":"lang","cat":"verbs"},
  {"en":"open","th":"poet","cat":"verbs"},
  {"en":"close","th":"pit","cat":"verbs"},
  {"en":"call (phone)","th":"tho","cat":"verbs"},
  {"en":"send","th":"song","cat":"verbs"},
  {"en":"receive","th":"rap","cat":"verbs"},
  {"en":"find","th":"ha","cat":"verbs"},
  {"en":"give","th":"hai","cat":"verbs"},
  {"en":"take","th":"ao","cat":"verbs"},
  {"en":"leave / go out","th":"ork","cat":"verbs"},
  {"en":"arrive","th":"theung","cat":"verbs"},
  {"en":"wait","th":"ror","cat":"verbs"},
  {"en":"meet","th":"phob","cat":"verbs"},
  {"en":"ask","th":"tham","cat":"verbs"},
  {"en":"answer","th":"tob","cat":"verbs"},
  {"en":"study","th":"rian","cat":"verbs"},
  {"en":"work","th":"tham ngan","cat":"verbs"},
  {"en":"play","th":"len","cat":"verbs"},
  {"en":"sing","th":"rong phleng","cat":"verbs"},
  {"en":"dance","th":"ten","cat":"verbs"},
  {"en":"laugh","th":"hua roh","cat":"verbs"},
  {"en":"cry","th":"rong hai","cat":"verbs"},
  {"en":"smile","th":"yim","cat":"verbs"},
  {"en":"worry","th":"pen huang","cat":"verbs"},
  {"en":"hurry","th":"reo reo","cat":"verbs"},
  {"en":"rest","th":"phak","cat":"verbs"},
  {"en":"exercise","th":"ork gam lang gai","cat":"verbs"},
  {"en":"shower","th":"ab nam","cat":"verbs"},
  {"en":"return","th":"glap","cat":"verbs"},
  {"en":"borrow","th":"yaem","cat":"verbs"},
  {"en":"try","th":"long / pha-ya-yam","cat":"verbs"},
  {"en":"check","th":"truat sob","cat":"verbs"},
  {"en":"change","th":"plian","cat":"verbs"},
  {"en":"choose","th":"leuak","cat":"verbs"},
  {"en":"use","th":"chai","cat":"verbs"},
  {"en":"start","th":"rerm","cat":"verbs"},
  {"en":"finish","th":"set","cat":"verbs"},
  {"en":"lose","th":"hai","cat":"verbs"},
  {"en":"good","th":"dee","cat":"adjectives"},
  {"en":"bad","th":"mai dee / chua","cat":"adjectives"},
  {"en":"beautiful","th":"suai","cat":"adjectives"},
  {"en":"cute","th":"narak","cat":"adjectives"},
  {"en":"big","th":"yai","cat":"adjectives"},
  {"en":"small","th":"lek","cat":"adjectives"},
  {"en":"tall","th":"soong","cat":"adjectives"},
  {"en":"short (height)","th":"tia","cat":"adjectives"},
  {"en":"long","th":"yao","cat":"adjectives"},
  {"en":"short (length)","th":"san","cat":"adjectives"},
  {"en":"wide","th":"gwang","cat":"adjectives"},
  {"en":"narrow","th":"kaep","cat":"adjectives"},
  {"en":"heavy","th":"nak","cat":"adjectives"},
  {"en":"light (weight)","th":"bow","cat":"adjectives"},
  {"en":"hot","th":"rorn","cat":"adjectives"},
  {"en":"cold","th":"yen","cat":"adjectives"},
  {"en":"warm","th":"oon","cat":"adjectives"},
  {"en":"fast","th":"reo","cat":"adjectives"},
  {"en":"slow","th":"cha","cat":"adjectives"},
  {"en":"easy","th":"ngai","cat":"adjectives"},
  {"en":"difficult","th":"yaak","cat":"adjectives"},
  {"en":"fun","th":"sanook","cat":"adjectives"},
  {"en":"boring","th":"na beua","cat":"adjectives"},
  {"en":"interesting","th":"na son jai","cat":"adjectives"},
  {"en":"tired","th":"neuy","cat":"adjectives"},
  {"en":"hungry","th":"hiu","cat":"adjectives"},
  {"en":"thirsty","th":"hiu nam","cat":"adjectives"},
  {"en":"full (after eating)","th":"im","cat":"adjectives"},
  {"en":"expensive","th":"phaeng","cat":"adjectives"},
  {"en":"cheap","th":"thook","cat":"adjectives"},
  {"en":"near","th":"klai","cat":"adjectives"},
  {"en":"far","th":"glai","cat":"adjectives"},
  {"en":"new","th":"mai","cat":"adjectives"},
  {"en":"old","th":"gao","cat":"adjectives"},
  {"en":"clean","th":"sa-aat","cat":"adjectives"},
  {"en":"dirty","th":"sok-ga-prok","cat":"adjectives"},
  {"en":"quiet","th":"ngiap","cat":"adjectives"},
  {"en":"noisy","th":"dang","cat":"adjectives"},
  {"en":"safe","th":"phlot-pai","cat":"adjectives"},
  {"en":"dangerous","th":"an-ta-rai","cat":"adjectives"},
  {"en":"correct","th":"thook-tong","cat":"adjectives"},
  {"en":"wrong","th":"phit","cat":"adjectives"},
  {"en":"same","th":"meuan","cat":"adjectives"},
  {"en":"different","th":"tang","cat":"adjectives"},
  {"en":"enough","th":"por","cat":"adjectives"},
  {"en":"more","th":"ik","cat":"adjectives"},
  {"en":"less","th":"noi long","cat":"adjectives"},
  {"en":"a lot / very","th":"mak","cat":"adjectives"},
  {"en":"a little","th":"nit noy","cat":"adjectives"},
  {"en":"full (not empty)","th":"tem","cat":"adjectives"},

  // ── Alphabet — Thai consonants ────────────
  {"en":"g/k · gaw gai","th":"gaw gai","script":"ก","cat":"alphabet","note":"mid class · initial g/k, final k"},
  {"en":"kh · kaw khai","th":"kaw khai","script":"ข","cat":"alphabet","note":"high class · aspirated k"},
  {"en":"kh · kaw kuat","th":"kaw kuat","script":"ฃ","cat":"alphabet","note":"high class · obsolete"},
  {"en":"kh · khaw khwai","th":"khaw khwai","script":"ค","cat":"alphabet","note":"low class · aspirated k"},
  {"en":"kh · khaw ra-khang","th":"khaw ra-khang","script":"ฆ","cat":"alphabet","note":"low class · aspirated k"},
  {"en":"ng · ngaw ngoo","th":"ngaw ngoo","script":"ง","cat":"alphabet","note":"low class · ng as in sing"},
  {"en":"j · jaw jaan","th":"jaw jaan","script":"จ","cat":"alphabet","note":"mid class"},
  {"en":"ch · chaw ching","th":"chaw ching","script":"ฉ","cat":"alphabet","note":"high class · aspirated ch"},
  {"en":"ch · chaw chaang","th":"chaw chaang","script":"ช","cat":"alphabet","note":"low class · aspirated ch"},
  {"en":"s · saw so-kho","th":"saw so-kho","script":"ซ","cat":"alphabet","note":"low class"},
  {"en":"ch · chaw cher","th":"chaw cher","script":"ฌ","cat":"alphabet","note":"low class · rare"},
  {"en":"y · yaw ying","th":"yaw ying","script":"ญ","cat":"alphabet","note":"low class"},
  {"en":"d · daw chada","th":"daw chada","script":"ฎ","cat":"alphabet","note":"mid class · rare"},
  {"en":"t · taw bpatak","th":"taw bpatak","script":"ฏ","cat":"alphabet","note":"mid class · rare"},
  {"en":"th · thaw thaan","th":"thaw thaan","script":"ฐ","cat":"alphabet","note":"high class · aspirated t, rare"},
  {"en":"th · thaw montho","th":"thaw montho","script":"ฑ","cat":"alphabet","note":"low class · rare"},
  {"en":"th · thaw phuu-thao","th":"thaw phuu-thao","script":"ฒ","cat":"alphabet","note":"low class · rare"},
  {"en":"n · naw nen","th":"naw nen","script":"ณ","cat":"alphabet","note":"low class · rare"},
  {"en":"d · daw dek","th":"daw dek","script":"ด","cat":"alphabet","note":"mid class"},
  {"en":"t · taw tao","th":"taw tao","script":"ต","cat":"alphabet","note":"mid class · unaspirated t"},
  {"en":"th · thaw thung","th":"thaw thung","script":"ถ","cat":"alphabet","note":"high class · aspirated t"},
  {"en":"th · thaw thahaarn","th":"thaw thahaarn","script":"ท","cat":"alphabet","note":"low class · aspirated t"},
  {"en":"th · thaw thong","th":"thaw thong","script":"ธ","cat":"alphabet","note":"low class · aspirated t"},
  {"en":"n · naw noo","th":"naw noo","script":"น","cat":"alphabet","note":"low class"},
  {"en":"b · baw baimai","th":"baw baimai","script":"บ","cat":"alphabet","note":"mid class"},
  {"en":"bp · bpaw bplaa","th":"bpaw bplaa","script":"ป","cat":"alphabet","note":"mid class · unaspirated p"},
  {"en":"ph · phaw phuung","th":"phaw phuung","script":"ผ","cat":"alphabet","note":"high class · aspirated p"},
  {"en":"f · faw faa","th":"faw faa","script":"ฝ","cat":"alphabet","note":"high class"},
  {"en":"ph · phaw phaan","th":"phaw phaan","script":"พ","cat":"alphabet","note":"low class · aspirated p"},
  {"en":"f · faw fan","th":"faw fan","script":"ฟ","cat":"alphabet","note":"low class"},
  {"en":"ph · phaw samphao","th":"phaw samphao","script":"ภ","cat":"alphabet","note":"low class · aspirated p"},
  {"en":"m · maw maak","th":"maw maak","script":"ม","cat":"alphabet","note":"low class"},
  {"en":"y · yaw yaak","th":"yaw yaak","script":"ย","cat":"alphabet","note":"low class"},
  {"en":"r · raw ruua","th":"raw ruua","script":"ร","cat":"alphabet","note":"low class · rolled r"},
  {"en":"l · law ling","th":"law ling","script":"ล","cat":"alphabet","note":"low class"},
  {"en":"w · waw waen","th":"waw waen","script":"ว","cat":"alphabet","note":"low class"},
  {"en":"s · saw sala","th":"saw sala","script":"ศ","cat":"alphabet","note":"high class · rare"},
  {"en":"s · saw ruusi","th":"saw ruusi","script":"ษ","cat":"alphabet","note":"high class · rare"},
  {"en":"s · saw suua","th":"saw suua","script":"ส","cat":"alphabet","note":"high class"},
  {"en":"h · haw hiip","th":"haw hiip","script":"ห","cat":"alphabet","note":"high class"},
  {"en":"l · law jula","th":"law jula","script":"ฬ","cat":"alphabet","note":"low class · rare"},
  {"en":"(vowel holder) · aw aang","th":"aw aang","script":"อ","cat":"alphabet","note":"mid class · holds vowels"},
  {"en":"h · haw nok-hook","th":"haw nok-hook","script":"ฮ","cat":"alphabet","note":"low class · rare"},

  // ── Sentences ──
  {"en":"Where are you going?","th":"bpai nǎi","script":"ไปไหน","cat":"sentences"},
  {"en":"I'm going to the market.","th":"bpai dtà-làad","script":"ไปตลาด","cat":"sentences"},
  {"en":"How much is this?","th":"nêe tâo-rài","script":"นี่เท่าไหร่","cat":"sentences"},
  {"en":"It's too expensive.","th":"phaeng bpai","script":"แพงไป","cat":"sentences"},
  {"en":"Can you reduce the price?","th":"lót raa-khaa dâi mǎi","script":"ลดราคาได้ไหม","cat":"sentences"},
  {"en":"I don't understand.","th":"mâi khâo-jai","script":"ไม่เข้าใจ","cat":"sentences"},
  {"en":"Please speak slowly.","th":"phûud cháa-cháa nòi dâi mǎi","script":"พูดช้าๆหน่อยได้ไหม","cat":"sentences"},
  {"en":"What is your name?","th":"khun chêu à-rai","script":"คุณชื่ออะไร","cat":"sentences"},
  {"en":"My name is …","th":"phǒm chêu …","script":"ผมชื่อ…","cat":"sentences","note":"male: phǒm · female: chǎn"},
  {"en":"I don't eat spicy food.","th":"phǒm mâi gin pèd","script":"ผมไม่กินเผ็ด","cat":"sentences"},
  {"en":"The food is delicious.","th":"aa-hǎan à-ròi","script":"อาหารอร่อย","cat":"sentences"},
  {"en":"I want to eat rice.","th":"yàak gin khâao","script":"อยากกินข้าว","cat":"sentences"},
  {"en":"Where is the toilet?","th":"hâwng-náam yùu tîi-nǎi","script":"ห้องน้ำอยู่ที่ไหน","cat":"sentences"},
  {"en":"I'm lost.","th":"phǒm lǒng thaang","script":"ผมหลงทาง","cat":"sentences"},
  {"en":"Please call a taxi.","th":"chêu-ay rîak tháek-sîi dâi mǎi","script":"ช่วยเรียกแท็กซี่ได้ไหม","cat":"sentences"},
  {"en":"How far is it?","th":"yùu glai mâi","script":"อยู่ไกลไหม","cat":"sentences"},
  {"en":"Turn left.","th":"lîaw sáai","script":"เลี้ยวซ้าย","cat":"sentences"},
  {"en":"Turn right.","th":"lîaw kwǎa","script":"เลี้ยวขวา","cat":"sentences"},
  {"en":"Go straight.","th":"bpai dtrong","script":"ไปตรง","cat":"sentences"},
  {"en":"I feel unwell.","th":"phǒm mâi sa-baai","script":"ผมไม่สบาย","cat":"sentences"},
  {"en":"Please help me.","th":"chêu-ay phǒm nòi","script":"ช่วยผมหน่อย","cat":"sentences"},
  {"en":"I want to go to the hospital.","th":"yàak bpai rohng-pha-yaa-baan","script":"อยากไปโรงพยาบาล","cat":"sentences"},
  {"en":"Can you speak English?","th":"phûud phaasǎa ang-grìd dâi mǎi","script":"พูดภาษาอังกฤษได้ไหม","cat":"sentences"},
  {"en":"A little bit.","th":"nit-nòi","script":"นิดหน่อย","cat":"sentences"},
  {"en":"I like Thailand.","th":"phǒm chôob meuang-thai","script":"ผมชอบเมืองไทย","cat":"sentences"},
  {"en":"It's very hot today.","th":"wan-née rawn mâak","script":"วันนี้ร้อนมาก","cat":"sentences"},
  {"en":"Check, please.","th":"gèp dtem dûay","script":"เก็บเต็มด้วย","cat":"sentences","note":"asking for the bill"},
  {"en":"Do you have …?","th":"mii … mǎi","script":"มี…ไหม","cat":"sentences"},
  {"en":"I would like …","th":"khǎw … nòi","script":"ขอ…หน่อย","cat":"sentences"},
  {"en":"See you again.","th":"phóp gan mài","script":"พบกันใหม่","cat":"sentences"},
  {"en":"Take care.","th":"duu lae dtua-eng dûay","script":"ดูแลตัวเองด้วย","cat":"sentences"},
  {"en":"Good luck!","th":"chôok dee","script":"โชคดี","cat":"sentences"},
  {"en":"Never mind.","th":"mâi bpen rai","script":"ไม่เป็นไร","cat":"sentences"},
  {"en":"I understand.","th":"khâo-jai láeo","script":"เข้าใจแล้ว","cat":"sentences"},
  {"en":"Not yet.","th":"yang","script":"ยัง","cat":"sentences","note":"also means 'still'"},
  {"en":"Already done.","th":"láeo","script":"แล้ว","cat":"sentences","note":"aspect particle: completed action"},
];